services:
  - type: web
    name: insta-clone
    env: node
    repo: https://github.com/devMayank1005/BACKEND-.git
    rootDir: insta-bcknd-clone
    buildCommand: cd insta-bcknd-clone/frontend && npm install && npm run build
    startCommand: cd insta-bcknd-clone && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
